import { Base64 } from "js-base64";

/**
 * Represents an attachment included with a message.
 */
export interface Attachment {
  /** The MIME type of the file (e.g., 'image/png'). */
  mimeType: string;
  /** The binary content of the file. */
  content: ArrayBuffer;
}

/**
 * Represents a message sent by the user.
 */
export interface UserMessage {
  /** Always set to "user" to identify the sender. */
  role: "user";
  /** The text content of the message, or null if only attachments are present. */
  content: string | null;
  /** List of files attached to the message. */
  attachments: Attachment[];
}

/**
 * Represents a request from the assistant to call a specific tool or function.
 */
export interface ToolCallRequest {
  /** Unique identifier for the tool call. */
  id: string;
  /** The name of the function/tool to call. */
  name: string;
  /** String containing arguments for the tool call. */
  arguments: string;
}

/**
 * Represents a message generated by the assistant.
 */
export interface AssistantMessage {
  /** Always set to "assistant" to identify the sender. */
  role: "assistant";
  /** Optional reasoning content (e.g., Chain of Thought), or null. */
  reasoningContent: string | null;
  /** The primary text response to the user. */
  content: string;
  /** List of tool calls requested by the assistant. */
  requestedToolCalls: ToolCallRequest[];
}

/**
 * Represents the result of a tool execution.
 */
export interface ToolResultMessage {
  /** Always set to "tool" to identify the sender. */
  role: "tool";
  /** The ID of the tool call this result corresponds to. */
  toolCallId: string;
  /** The text content returned by the tool. */
  content: string;
}

/**
 * Type representing all possible message roles.
 */
export type Message = UserMessage | AssistantMessage | ToolResultMessage;

/**
 * Type alias for values that should be excluded from history processing.
 * Useful for conditionals inside message arrays.
 */
export type ExcludedValues = boolean | null | undefined;

/**
 * Represents the history of a conversation, potentially containing
 * non-message values (like booleans) that need filtering.
 */
export type History = Array<Message | ExcludedValues>;

/**
 * Prepares a chat history array for transmission to an OpenAI-compatible Chat Completions API.
 *
 * @param instructions - Optional system prompt instructions to prepend.
 * @param history - The raw history array containing messages and potential excluded values.
 * @returns A formatted array of message objects ready for an API request.
 */
export function prepareHistory(instructions: string | null, history: History): object[] {
  const filtered = history.filter((i) => typeof i !== "boolean" && i !== null && i !== undefined);
  const prepared: object[] = filtered.map((msg) => {
    switch (msg.role) {
      case "assistant":
        return {
          role: "assistant",
          reasoning_content: !!msg.reasoningContent ? msg.reasoningContent : undefined,
          content: msg.content,
          tool_calls:
            msg.requestedToolCalls.length > 0
              ? msg.requestedToolCalls.map((call) => {
                  return {
                    id: call.id,
                    type: "function",
                    function: {
                      name: call.name,
                      arguments: call.arguments,
                    },
                  };
                })
              : undefined,
        };
      case "user":
        return {
          role: "user",
          content: [
            msg.content !== null && { type: "text", text: msg.content },
            ...msg.attachments.map((attachment) => {
              const base64 = Base64.fromUint8Array(new Uint8Array(attachment.content), false);
              return {
                type: "image_url",
                image_url: { url: `data:${attachment.mimeType};base64,${base64}` },
              };
            }),
          ].filter((c) => !!c),
        };
      case "tool":
        return {
          role: "tool",
          tool_call_id: msg.toolCallId,
          content: msg.content,
        };
    }
  });

  if (instructions !== null && instructions.length) {
    prepared.unshift({
      role: "system",
      content: instructions,
    });
  }

  return prepared;
}
